# Generated by Django 5.2.4 on 2025-08-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brandtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('category', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkouttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=250, null=True)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('place', models.CharField(max_length=250, null=True)),
                ('landmark', models.CharField(max_length=250, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('shippingcharge', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('total_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contacttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='countrytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deliverytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('vehicle', models.CharField(max_length=250, null=True)),
                ('vehicle_number', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('created', models.CharField(max_length=50, null=True)),
                ('updated', models.CharField(max_length=50, null=True)),
                ('opening_stock', models.CharField(max_length=50, null=True)),
                ('current_stock', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outfordeliverytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=250, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.deliverytable')),
            ],
        ),
        migrations.CreateModel(
            name='checkoutitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.checkouttable')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.productstable')),
            ],
        ),
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.productstable')),
            ],
        ),
    ]
